# Node 基础镜像，构建时安装 npm 依赖，运行由 run1.sh 执行 npm run start。
# 示例：docker build -f conf/dockerfile/Dockerfile.base.node --build-arg IN_CHINA=true -t mynode:base .

ARG MIRROR=
ARG IMAGE_TYPE=node
ARG BUILD_IMAGE=node
ARG BUILD_TAG=22-slim
ARG RUN_IMAGE=node
ARG RUN_TAG=22-slim
ARG IN_CHINA=false
ARG APP_PORT=8080
ARG APP_WORKDIR=/app
ARG APP_USER=1000
ARG APP_UID=1000
ARG APP_GID=1000
ARG BUILD_URL=https://gitee.com/xiagw/deploy.sh/raw/main/conf/dockerfile/root/opt/build.sh
ARG BUILD_OUTPUT_DIR=/build_output

## 阶段 1
# FROM ${MIRROR}${BUILD_IMAGE}:${BUILD_TAG} AS builder
# WORKDIR /app
# 只复制 package.json 和锁文件（利用缓存的关键）
# COPY package.json package-lock.json* ./
# 安装依赖（如果 package.json 没变，这一步和上面那步都会直接走缓存）
# RUN npm ci

## 阶段 2
FROM ${MIRROR}${RUN_IMAGE}:${RUN_TAG} AS final
ARG IN_CHINA
ARG BUILD_URL
ARG BUILD_OUTPUT_DIR
ARG APP_PORT
ARG APP_WORKDIR
ARG APP_USER

# 设置时区和语言
# ENV TZ=Asia/Shanghai \
#     LANG=C.UTF-8


# 设置工作目录
WORKDIR /app

# 暴露端口
EXPOSE 8080 8081
VOLUME ["/app"]
# 使用非 root 用户运行应用
# USER node

# 设置健康检查
# HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
#     CMD curl -f http://localhost:8080/ || exit 1

# 构建脚本
RUN --mount=type=bind,target=/src,rw \
    set -xe; \
    BUILD_SH=/src/root/opt/build.sh; \
    [ -f $BUILD_SH ] || BUILD_SH=build.sh; \
    [ -f $BUILD_SH ] || curl -fLo $BUILD_SH $BUILD_URL; \
    bash $BUILD_SH

CMD ["bash", "/opt/run0.sh"]
## docker build -t registry-vpc.cn-hangzhou.aliyuncs.com/flyh5/flyh5:node-18-base \
## -f Dockerfile.node.base --progress=plain --build-arg IN_CHINA="true" .

# ONBUILD 指令
ONBUILD COPY --chown=1000:1000 . /app/
ONBUILD RUN if [ -f /opt/onbuild.sh ]; then bash /opt/onbuild.sh; fi
