# Redis 基础镜像，可通过 REDIS_PASSWORD 配置密码。
# 示例：docker build -f conf/dockerfile/Dockerfile.base.redis -t redis:base . && docker run -e REDIS_PASSWORD=xxx redis:base

ARG MIRROR=
ARG BUILD_IMAGE=redis
ARG BUILD_TAG=latest
ARG RUN_IMAGE=redis
ARG RUN_TAG=latest

ARG IN_CHINA=false
ARG INSTALL_NGINX=false
ARG BUILD_URL=https://gitee.com/xiagw/deploy.sh/raw/main/conf/dockerfile/root/opt/build.sh

# FROM ${MIRROR}${BUILD_IMAGE}:${BUILD_TAG} AS builder
# ARG IN_CHINA
# ARG INSTALL_NGINX
# ARG BUILD_URL

FROM ${MIRROR}${RUN_IMAGE}:${RUN_TAG} AS final
ARG IN_CHINA
ARG INSTALL_NGINX
ARG BUILD_URL

LABEL MAINTAINER="xiagw <fxiaxiaoyu@gmail.com>"

ARG TZ=UTC

ENV TZ=${TZ}

VOLUME /data

EXPOSE 6379
WORKDIR /data

RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    --mount=type=bind,target=/src,rw \
    set -xe; \
    BUILD_SH=/src/root/opt/build.sh; \
    [ -f $BUILD_SH ] || BUILD_SH=build.sh; \
    [ -f $BUILD_SH ] || curl -fLo $BUILD_SH $BUILD_URL; \
    bash $BUILD_SH

# COPY ./root/ /
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
# CMD ["redis-server"]
