# Redis 基础镜像，可通过 REDIS_PASSWORD 配置密码。
# 示例：docker build -f conf/dockerfile/Dockerfile.base.redis -t redis:base . && docker run -e REDIS_PASSWORD=xxx redis:base

ARG MIRROR=
ARG IMAGE=redis
ARG TAG=latest
FROM ${MIRROR}${IMAGE}:${TAG}

LABEL MAINTAINER="xiagw <fxiaxiaoyu@gmail.com>"

ARG TZ=UTC

ENV TZ=${TZ}

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

VOLUME /data

EXPOSE 6379

# COPY ./root/ /
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
# CMD ["redis-server"]
