# Redis 基础镜像，可通过 REDIS_PASSWORD 配置密码。
# 示例：docker build -f conf/dockerfile/Dockerfile.base.redis -t redis:base . && docker run -e REDIS_PASSWORD=xxx redis:base

ARG MIRROR=
ARG BUILD_IMAGE=redis
ARG BUILD_TAG=latest
ARG RUN_IMAGE=redis
ARG RUN_TAG=latest

# FROM ${MIRROR}${BUILD_IMAGE}:${BUILD_TAG}
FROM ${MIRROR}${RUN_IMAGE}:${RUN_TAG}

LABEL MAINTAINER="xiagw <fxiaxiaoyu@gmail.com>"

ARG TZ=UTC

ENV TZ=${TZ}

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

VOLUME /data

EXPOSE 6379

# COPY ./root/ /
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
# CMD ["redis-server"]
