## arch: x86_64
ARG IMAGE_NAME=redis:latest

## arch: arm64
# ARG IMAGE_NAME=arm64v8/redis:latest

FROM ${IMAGE_NAME}

ARG TZ=UTC

ENV TZ ${TZ}

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

VOLUME /data

EXPOSE 6379

# COPY ./root/ /
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
# CMD ["redis-server"]
