ARG BASE_IMAGE=redis
ARG IMAGE_VERSION=latest
FROM ${BASE_IMAGE}:${IMAGE_VERSION}

LABEL MAINTAINER="xiagw <fxiaxiaoyu@gmail.com>"

ARG TZ=UTC

ENV TZ=${TZ}

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

VOLUME /data

EXPOSE 6379

# COPY ./root/ /
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
# CMD ["redis-server"]
