# Python 基础镜像，工作目录 /app，可 COPY requirements.txt 后 ONBUILD 执行 onbuild.sh。
# 示例：docker build -f conf/dockerfile/Dockerfile.base.python --build-arg PYTHON_VERSION=3.12 -t mypy:base .
ARG MIRROR=
ARG BUILD_IMAGE=python
ARG BUILD_TAG=3.12-slim
ARG RUN_IMAGE=python
ARG RUN_TAG=3.12-slim

# FROM ${MIRROR}${BUILD_IMAGE}:${BUILD_TAG}
FROM ${MIRROR}${RUN_IMAGE}:${RUN_TAG}

# Set Timezone
ARG TZ=UTC
ENV TZ=${TZ}
# Set Python Environment Variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONFAULTHANDLER=1 \
    PYTHONHASHSEED=random \
    PYTHONIOENCODING=UTF-8

WORKDIR /app
COPY requirements.txt /app/
## install uv
# RUN curl -LsSf https://astral.sh/uv/install.sh | sh
## set python mirror
# RUN pip install --no-cache-dir -r requirements.txt

ONBUILD COPY ./root/ /
ONBUILD RUN if [ -f /opt/onbuild.sh ]; then bash /opt/onbuild.sh; else :; fi