FROM nginx:alpine

# If you're in China, set IN_CHINA to true.
ARG IN_CHINA=false
ARG CHANGE_SOURCE=false
ARG INSTALL_NGINX=true

EXPOSE 80 81 443
WORKDIR /app

# COPY ./root/opt/build.sh /opt/build.sh
RUN set -xe; \
    curl -fLo /opt/build.sh https://gitee.com/xiagw/deploy.sh/raw/main/conf/dockerfile/root/opt/build.sh; \
    sh /opt/build.sh

ONBUILD COPY ./root/ /
ONBUILD RUN [ -f /opt/onbuild.sh ] && sh /opt/onbuild.sh