- name: Install packages for EDA
  hosts: all
  become: true
  vars:
    username: ops
    host_name: node11
    host_name_server: node11
    firewall_start: false
    firewall_rule: disable_out
    nis_server: true
    eda_home: /home/eda
    itcad_home: /home/ITCAD

  # roles:
  #   - xiagw.eda

  tasks:

    - name: Copy README.md
      ansible.builtin.copy:
        src: "../README.md"
        dest: "{{ itcad_home }}/"
        mode: "0644"
        owner: "1000"
        group: "1000"
      when: "ansible_hostname == host_name_server"

    - name: Copy admin.sh
      ansible.builtin.copy:
        src: "../admin.sh"
        dest: "{{ itcad_home }}/"
        mode: "0755"
        owner: "1000"
        group: "1000"
      when: "ansible_hostname == host_name_server"

    - name: Copy dir server/eda/
      ansible.builtin.copy:
        src: "server/eda/"
        dest: "{{ eda_home }}/"
        mode: "0644"
        owner: "1000"
        group: "1000"
      when: "ansible_hostname == host_name_server"

    - name: Copy dir server/etc/
      ansible.builtin.copy:
        src: "server/etc/"
        dest: "/etc/"
        mode: "0644"
        owner: "0"
        group: "0"
      when: "ansible_hostname == host_name_server"

    - name: File permission /eda/synopsys/license/startlic.sh
      ansible.builtin.file:
        name: "{{ eda_home }}/synopsys/license/startlic.sh"
        mode: "0755"
        owner: "1000"
        group: "1000"
      when: "ansible_hostname == host_name_server"

    - name: Copy dir client/etc/
      ansible.builtin.copy:
        src: "client/etc/"
        dest: "/etc/"
        mode: "0644"
        owner: "0"
        group: "0"

    - name: Copy dir client/usr/bin/
      ansible.builtin.copy:
        src: "client/usr/bin/"
        dest: "/usr/bin/"
        mode: "0755"
        owner: "0"
        group: "0"

    - name: Enable vncserver 1 2 3
      ansible.builtin.systemd:
        # state: stopped
        enabled: true
        name: "{{ item }}"
      with_items:
        # - vncserver@:1
        # - vncserver@:2
        # - vncserver@:3
        - wg-quick@wg0
      tags: qy

    - name: Firewall disable output
      ansible.builtin.command: /usr/bin/fw.sh {{ firewall_rule }}
      when: firewall_start
      register: result
      changed_when: result.rc == 0
      tags: fw
