---
# tasks file for roles/xiagw.autofs
- name: Configure autofs nis nfs client
  when: ansible_os_family == "Debian"
  block:
    - name: Install autofs nfs-common (Debian)
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - autofs
          - nfs-common
          - nis
          - nscd

    - name: Copy auto.data
      ansible.builtin.template:
        src: templates/auto.data.j2
        dest: /etc/auto.data
        mode: '0644'
        owner: root
        group: root

    - name: Copy auto.home
      ansible.builtin.template:
        src: templates/auto.home.j2
        dest: /etc/auto.home
        mode: '0644'
        owner: root
        group: root

    - name: Remove stale NIS line in /etc/yp.conf
      ansible.builtin.lineinfile:
        dest: /etc/yp.conf
        regexp: '^domain\s+.*\s+server\s+'
        state: absent

    - name: Set NIS domain in /etc/yp.conf
      ansible.builtin.lineinfile:
        dest: /etc/yp.conf
        line: 'domain  {{ autofs_nis_domain }}  server {{ autofs_nis_server }}'
      notify: Systemctl restart nis

    - name: Add pam_mkhomedir to common-session
      ansible.builtin.lineinfile:
        dest: /etc/pam.d/common-session
        regexp: '^session\s+optional\s+pam_mkhomedir.so'
        line: 'session	optional			pam_mkhomedir.so skel=/etc/skel umask=077'
        insertafter: '^session\s+(required|optional)\s+pam_unix.so'

    - name: Add nis to nsswitch.conf
      ansible.builtin.lineinfile:
        dest: /etc/nsswitch.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^passwd:\s+', line: 'passwd:         compat systemd nis' }
        - { regexp: '^group:\s+', line: 'group:          compat systemd nis' }
        - { regexp: '^shadow:\s+', line: 'shadow:         compat nis' }
        - { regexp: '^hosts:\s+', line: 'hosts:          files nis mdns4_minimal [NOTFOUND=return] dns myhostname' }
      notify: Systemctl restart nis

    - name: Copy auto.master
      ansible.builtin.copy:
        src: files/auto.master
        dest: /etc/auto.master
        mode: '0644'
        owner: root
        group: root
      notify: Systemctl restart autofs
